### PR TITLE
replace symbols with svg icons

### PR DESCRIPTION
**Pull request by kazzarin**
I figured just using svgs could sidestep any encoding issues with symbols as seen in #191 (and look nicer)
- Used font awesome icons similar in style as the existing ones

Also learned that `svgAssets2` was a thing
and `svgAssets` is actually just symbols? 🤔

### CODE REVIEW

**Comment by hohMiyazawa** [comment]
``svgAssets`` is currently very poorly named

**Comment by kazzarin** [comment]
>svgAssets is currently very poorly named

Perhaps I could go through and convert the remaining `svgAssets` symbols that are still used to `svgAssets2` svgs and then rename `svgAssets2` to something like `icons`.

**Comment by hohMiyazawa** [comment]
Maybe just a rename, not sold on converting those to SVGs.
``unicodeAssets``?

**Comment by kazzarin** [comment]
>Maybe just a rename,
>unicodeAssets

I suppose, though I don't see the point of maintaining both

>not sold on converting those to SVGs.

I realize I didn't attach any screenshots with this PR. Maybe I'll write the conversion anyways as a draft PR with proper side-by-side comparisons to better demonstrate an improvement.

**Pull request merged**
