### PR TITLE
Forum thread likes

### PR DESCRIPTION
**Pull request by synthtech**
Copied the code for displaying more likes on thread comments to make it work for the main thread post.

Main difference is I changed the API call to only get the first 20 users, so it doesn't try adding hundreds of more users to the `.users` list that won't be displayed anyways.

The other change prevents the list of users from appearing when hovering over the user avatars.

### CODE REVIEW

**Comment by hohMiyazawa** [comment]
Couple of things:
1. queryselectorAll, and then looping, is perhaps not the right approach here, as having multiple main posts on a page is currently something that doesn't happen. Wouldn't want the script to make a mess if that changes.

2. (not blocking merging) Currently, the view updates after an onclick. Is that sane to do when only loading a fixed portion of the likes? With some special casing, an API call can be saved there when a user liking/unliking will not affect the data shown.

**Comment by hohMiyazawa** [comment]
Eh, it's working code, so details can be ironed out later.

**Comment by hohMiyazawa** [comment]
And done with those two things.

**Comment by synthtech** [comment]
Ah thanks for fixing that. I got sidetracked looking into splitting it into its own module so it wouldn't need to be in the setinterval loop.

**Comment by hohMiyazawa** [comment]
That would indeed be cleaner. The reason the the original forumCommentLike stuff wasn't is that the comments visible on the page changes dynamically. But the main post itself doesn't need that.

**Pull request merged**
