### PR TITLE
Japanese translation update

### PR DESCRIPTION
**Pull request by SoulBlade172**
Most of the unique keys have been translated to some degree of accuracy. Japanese is not my first language, so I deeply apologise if there are any errors in the translations. The remaining and special keys will be done at another time.

Keys to translate later:
Need context of/unsure of formatting
"$button_run": "Run",
"$button_add": "Add",
"$notifications_showHoh": "Show hoh notifications", (I do not know what hoh means)
"$compare_hoh": "Show hoh compare",
"$review_reviewTitle": "Review of {0} by\u00a0{1}", (I am not sure what the \u00a0 is and how to fit it into the translation)

Do later (most of these are long sentences and harder to translate)
"$forumMedia_backlink": "Add a link back to a work's database page on its forum feed",
"$settings_export_description": "Might come in handy to keep a backup if you do stuff like wiping your browser cache/storage, which 
will wipe your Automail settings too",
"$settings_CSSadd": "Add custom CSS to your profile. This will be visible to others with the script.",
"$settings_CSSlinkTip": "(You can also use a direct link to a stylesheet)",
"$settings_pinnedActivity": "Add a pinned activity to your profile",
"$setting_moreStats": "Show an additional tab on the stats page",
"$setting_compare": "Replace the native comparison feature",
"$setting_CSSsmileyScore": "Give smiley ratings distinct colours","$setting_CSSmobileTags": "Don't hide tag voting from media pages on mobile",
"$setting_infoTable": "Use a two-column table layout for info on media pages",
"$setting_reinaDark": "Add a High Contrast Dark site theme [by Reina]",
"$cssTooBig": "Custom CSS is over 1MB. Make it smaller, or use a link instead.",
"$jsonTooBig": "Profile JSON is over 1MB",
"$debug_tip": "(Hey, it would be nice if you include this file when you report bugs. Makes my life easier)",
"$profileBackground_help1": "Set a profile background, examples:",
"$profileBackground_help2": "Tip: Use a colour with transparency, to work better with both light and dark themes. Example:",
"$profileBackground_help3": "Tip2: Do you want a faded image, staying fixed in place, and filling the screen? This is how:",
"$notification_forumCommentLike": " liked your comment, in the forum thread ",
"$notification_forumMention": " mentioned you, in the forum thread ","$timeline_search_description": "Looking for the activities of someone else?",
"$noScrollPosts_description": "Display all status posts in full regardless of their length",
"$ALbuttonReload_description": "Make the 'AL' button reload the feeds on the homepage",
"$piracy_message": "THIS BE BAD LINK, IT'S NOW VEWY DISPOSED OF OwO (click the report button to call the mods on this naughty user)",
"$recs_description": "Each pair is one you like + one you haven't started\nBest match first",
"$module_unicodifier_description": "Convert emojis so they work on anilist",
"$module_unicodifier_extendedDescription": "Anilist doesn't handle some Unicode characters correctly, leading to truncated posts. This module coverts them to HTML entity escape codes instead, which the site can handle (they can easily do this themselves if they want to)\nOriginal idea by the great GoBusto: https://files.kiniro.uk/unicodifier.html","$stats_animeOnList": "Anime on list: ",
"$stats_mangaOnList": "Manga on list: ","$query_autorecs_info": "Top picks, based on your ratings, the ratings of others, and the recommendation database. Best matches on top",
"$mobileFriendly_description": "Mobile Friendly mode. Disables some modules not working properly on mobile, and adjusts others",

Not sure on how to translate
"$stats_animeOnList": "Anime on list: ",
"$stats_mangaOnList": "Manga on list: ",
"$stats_instances_unique": "no two scores alike",

### CODE REVIEW

**Comment by hohMiyazawa** [comment]
>  Need context of/unsure of formatting

>"$button_run": "Run",
It's a button under profile > stats > more stats > various queries. Intended to be used for buttons starting some kind of process.
>"$button_add": "Add",
Used in for instance settings > apps > Block stuff in the home feed. Intended for buttons that add another item to a list.
>"$notifications_showHoh": "Show hoh notifications", (I do not know what hoh means)
> "$compare_hoh": "Show hoh compare",
hoh is my name, meaning this is my alternate version of an existing feature. Could be something like "Show alternate notifications" instead.
"$review_reviewTitle": "Review of {0} by\u00a0{1}", (I am not sure what the \u00a0 is and how to fit it into the translation)
It's a space that should not be used for line breaks. It's to keep "by" and the name from ending up on different lines. Free feel to use a regular space instead.

**Review by hohMiyazawa — APPROVED** [review]

**Comment by SoulBlade172** [comment]
Thank you for the swift reply. I will edit the maintainer and note on the next commit when I get to translating the remaining keys. Thank you for also helping me with the keys I was not too sure with.

**Comment by SoulBlade172** [comment]
The second update should be the final update for now, translating all of the remaining keys and adding some staff role translations. If there are any errors or you need me for something else, please let me know.

**Comment by SoulBlade172** [comment]
The update to the Japanese translation of Automail was released recently, and I realised there was an error in the work I did. In the activity feed on the home page, the title would incorrectly be at the end of the sentence instead of the beginning, like this: 
　を見る予定です。 きみと、波にのれたら
Where it should be:
 きみと、波にのれたらを見る予定です。
Here is an image of it if you want to see it - 
image

Is there a way I can fix this? I would greatly appreciate if you can guide me as to how to.

Furthermore, I noticed that the English language had more keys.
image
The English json has 513 lines, so are the extra keys coming from somewhere else? I would like to see if the remaining keys is something I can translate as well.

My apologies to bother you again and thank you for your time.

**Comment by hohMiyazawa** [comment]
The remaining keys are the "special" staff role keys, but they aren't in the English file since they are already in English.

To fix the order problem, you have two options:
1. Rewrite the sentence to have both the name and title at the same location as the English. (I know this can not be forced in all languages)
2. Give me a *very clear* specification for how the sentence should be ordered so I can write a special solution.

**Comment by SoulBlade172** [comment]
I honestly do not know how to do the first option you provided, so I will give you a specification on how the sentence should be ordered. My apologies.

In Japanese, the grammar is essentially in the opposite order as compared to English, with the verbs at the end of the sentence and the topic at the front. Currently as you know the title incorrectly shows at the end of the sentence/verb. In most cases, the topic would be at the front, with "を" following it and ending with the verb. So it would look like this for each of the keys:
"$listActivity_MreadChapter": [manga title] の第 {0} 章を読みました。
"$listActivity_MwatchedEpisode": [anime title] の第 {0} 話を見ました。
"$listActivity_planningManga": [manga title] を読む予定です。
"$listActivity_planningAnime": [anime title] を見る予定です。
"$listActivity_completedManga": [manga title] を完成させました。
"$listActivity_completedAnime": [anime title] を完成させました。
"$listActivity_repeatedManga": [manga title] を再読しました。
"$listActivity_repeatedAnime": [anime title] を再視聴しました。
"$listActivity_pausedManga": [manga title] を読むのを一時中断しました。
"$listActivity_pausedAnime": [anime title] を見るのを一時中断しました。(I made an error on the two paused keys, I added the extra を it needed at the beginning)
"$listActivity_droppedManga": [manga title] をドロップしました。
"$listActivity_droppedAnime": [anime title] をドロップしました。
"$listActivity_MdroppedManga": [manga title] の {0} をドロップしました。
"$listActivity_MdroppedAnime": [anime title] の {0} をドロップしました。
"$listActivity_MrepeatingManga": [manga title] の第 {0} 章を再読しました。
"$listActivity_MrepeatingAnime": [anime title] の第 {0} 章を再視聴しました。

I have not noticed any other keys that are erroneously displayed in the same manner.

I hope how I have specified it is clear enough. If not, please do let me know. I apologise for the troubles I have caused.

**Comment by hohMiyazawa** [comment]
@SoulBlade172 Can I safely assume the title will always be first?

Will the final structure be: [username] [title] text

**Comment by SoulBlade172** [comment]
For keys like this, the title should be first. I am not aware of other keys that I have not mentioned where the structure would be different.

**Comment by hohMiyazawa** [comment]
I usually try to put variable stuff as {0} and {1} and so on, but it's difficult to do when replacing native stuff like activities.

One attempted fix is live now. If it's okay, but translation changes in a new pull request.

**Comment by SoulBlade172** [comment]
Understood, thank you for your time and efforts.

**Comment by hohMiyazawa** [comment]
Just linking this PR to the main translation thread https://github.com/hohMiyazawa/Automail/issues/69

**Pull request merged**
