### PR TITLE
Update portuguese translation

### PR DESCRIPTION
**Pull request by Sam-Oak**
i stopped being lazy and added the staff credit translations.
also, the keys `$menu_animelist` (lista de anime) and `$menu_mangalist` (lista de manga) on the website are uppercase, but the preposition "de" should be lowercase in PT
image

### CODE REVIEW

**Comment by hohMiyazawa** [comment]
That's due to native Anilist CSS having ``text-transform: capitalize``. That means it can't be purely implemented through translation keys, and some codes to override the Anilist defaults must be added.

I can add that, but can you update the keys ``"$menu_home, $menu_profile, $menu_animelist, $menu_mangalist, $menu_browse, $menu_forum`` to use the exact capitalisation you want? That is, ``"$menu_animelist": "lista de anime"`` must be ``"$menu_animelist": "Lista de Anime"`` if you want it to appear as "Lista de Anime" instead of "lista de anime" after the change.

**Comment by hohMiyazawa** [comment]
Added it as a pull request to your repo, https://github.com/Sam-Oak/Automail/pull/1, so this can be merged as a package afterwards.

**Review by hohMiyazawa — APPROVED** [review]

**Comment by hohMiyazawa** [comment]
@MrJako2001 Is the uppercasing of "De" a problem in the Spanish translation too?

**Comment by hohMiyazawa** [comment]
Also, slightly curious about this, since your profile says Brazil: ``"notes": "tentei usar português europeu"``. In case you're having a style choice dilemma, it's explicitly allowed to have different language variations. See ``src/data/langauges/English_US.json`` for an example how this can be done.

**Comment by Sam-Oak** [comment]
EU and BR portuguese differ considerably in speech, but grammar and vocabulary are essentially the same, so i don't think it needs to have a different variation. In Wikipedia, for example, there is no separation between PT-EU and PT-BR. I choose to translate closer to EU-PT as it's more resilient to the use of foreign words, while PT-BR often doesn't translate some terms such as "login", "staff", "backup" etc.

**Comment by hohMiyazawa** [comment]
Ah, thank you for explaining.

**Comment by MrJako2001** [comment]
> @MrJako2001 Is the uppercasing of "De" a problem in the Spanish translation too?

Sorry for the delay, yes indeed.

**Pull request merged**
