### PR TITLE
mangaGuess - Fix infinite loop on setTimeout

### PR DESCRIPTION
**Pull request by nategasm**
mangaGuess was infinite looping on manga that did not have the "Releasing" status, so replaced the setTimeout with a Mutationobserver.
Most of the changes shown are just increasing the indentation. The actual changes are on line 2, 17-29, 135-141, nothing else was touched.

Question, should mangaGuess still run on "releasing" manga that already have a value for chapters?
Example: https://anilist.co/manga/97816/Otonari-Complex/

PS There's a few more of these loops in other modules which I may get around to.

### CODE REVIEW

**Comment by hohMiyazawa** [comment]
Is there an actual bug here?
Anilist loads data asynchronously, so media data may turn up suddenly at any moment, even long after the rest of the page has loaded.
So the current code just checks if there's a releasing manga currently on the page, as long as we are on a manga page.
The replacement code does that too, but runs the check on every element change instead of every 200ms. I'm not sure that's performant.

**Comment by nategasm** [comment]
I understand it loads asynchronously, that's why the replacement code only creates an observer if the data is missing and disconnects it as soon as the status is found. This means no matter what order the data loads, we can stop observing as soon as possible. The observer is re-established between page loads (Only if required). This works on both Releasing manga and manga with other status (Finished, Not Yet Released etc.).

The current code only stops the timeout loop for manga with Releasing status, however keeps running in an infinite loop on manga with any other status because 'Releasing' is never found.

Specifically this part
```
	let possibleReleaseStatus = Array.from(
		document.querySelectorAll(".data-set .value")
	).find(
		element => element.innerText.match(/^Releasing/)
	);
	if(!possibleReleaseStatus){
		setTimeout(mangaGuess,200);
		return
	}
```

Regarding performance, I've only ever noted the observer triggering at most 1 extra time when the status isn't found. Whereas the timeout was triggered a few more times when not found. This might require more testing though since it's rare for the observers/timeouts to be triggered in the first place, at least on my machine/connection.

**Comment by hohMiyazawa** [comment]
Leaving this open until I have gone through a round of inspecting exactly what happens on page load.

**Comment by hohMiyazawa** [comment]
My main problem with this is that it observes ``subtree: true`` on ``document.body``. The scope is just too wide.

**Comment by nategasm** [comment]
Due to the node structure of `.sidebar .data` subtree: false will only partially work. So just reduced the scope of the observer to  `.sidebar .data`

**Comment by hohMiyazawa** [comment]
Guaranteeing that the sidebar doesn't have a lot of node activity is a lot easier than making sure the entire page has low node activity, so that's fine.

**Pull request merged**
