### PR TITLE
anilistAPI: handle error if request fails

### PR DESCRIPTION
**Pull request by synthtech**
catch errors if fetch itself fails

### CODE REVIEW

**Comment by hohMiyazawa** [comment]
What exactly happens here then?
Network errors are common and acceptable, so ideally the calling module should be informed that the fetch failed and that it isn't going to get any data, and continue on from there. Other modules should be allowed to continue doing their thing even if one modules doesn't get its data.

I want a few sentences here what the big picture error handling idea is.

**Comment by synthtech** [comment]
It was an oversight on my part that network errors weren't handled. I spent a lot of time focusing on http errors (the kind that still returns a response) and so it (almost) always returns the data response to the calling function.

Since the api shutdown today it came to my attention that failures at the network level (no response given) were still returned to the calling function and would then error out because there was nothing to parse (no data, no error objects).

So rethinking this through, I could instead pass in some kind of fake error object instead of throwing if that's preferable so modules could handle it as normal.

**Comment by hohMiyazawa** [comment]
Yeah, a lot of modules have (or need) ways to clean up after themselves, or have a fallback solution.

Sending them a fake error object would be preferable. (the old API does this, I think, but not very cleanly)

**Comment by synthtech** [comment]
I'll probably send something back like this:
https://github.com/hohMiyazawa/Automail/blob/1505cdf79d95da875f5340c2c8bbe718919ba684/src/graphql.js#L833-L836

and have the message be the returned network error (maybe omitting the status or set to null)

**Comment by hohMiyazawa** [comment]
Sounds good

**Comment by synthtech** [comment]
i hope it works, api seems to be back up for me just as i wanted to test it lol

**Pull request merged**
